language: node_js

cache:
  yarn: false

before_install:
  - yarn global add typescript
  - yarn global add ava
  - yarn global add tslint
  - yarn global add typedoc
  - yarn

script: yarn test

node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
